# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader:
    default_format: json
  zone:
    - { path: ^/exercise* }
  view:
    view_response_listener:  force
    default_engine: json
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
      \InvalidArgumentException: 400
    messages:
      Doctrine\ORM\EntityNotFoundException: true
      \InvalidArgumentException: true
  format_listener:
    rules:
      - { path: ^/exercise, prefer_extension: true, fallback_format: json, priorities: [ json ] }