lexik_jwt_authentication:
    secret_key: 'kaJr7ZyQSaedNFc109M8JGY7bEpa02WtO7iOVzp4hYFqgIpVvFgQW4b9FWWhNK8zsAoWu3Na1AcbD7WVuPjV8RrkXKCQpxq1AssTkQ'
    token_ttl: 900
    user_identity_field: email
    encoder:
        signature_algorithm: HS256
