api_login_check:
    path: /auth/login

index:
    path: /
    methods: [ get ]
    controller: App\Controller\IndexController::index

exercise:
    type: rest
    resource: App\Controller\ExerciseController
